cypcore/Services/SerfService.cs, cypcore/cypcore.csproj
fixes bug when running serf on case-sensitive file systems
=> serf platform folders and file path

cypcore/Consensus/Blockmania/BitSet.cs, cypcore/Consensus/Blockmania/Graph.cs, cypcore/Consensus/Blockmania/Messages/Commit.cs, cypcore/Consensus/Blockmania/Messages/Message.cs, cypcore/Consensus/Blockmania/Messages/NewView.cs, cypcore/Consensus/Blockmania/Messages/PrePrepare.cs, cypcore/Consensus/Blockmania/Messages/Prepare.cs, cypcore/Consensus/Blockmania/Messages/ViewChange.cs, cypcore/Consensus/Blockmania/PBFT.cs, cypcore/Consensus/Blockmania/PBFTOptions.cs, cypcore/Consensus/Blockmania/State.cs, cypcore/Consensus/Blockmania/States/Final.cs, cypcore/Consensus/Blockmania/States/Hnv.cs, cypcore/Consensus/Blockmania/States/PrePrepared.cs, cypcore/Consensus/Blockmania/States/Prepared.cs, cypcore/Consensus/Blockmania/States/View.cs, cypcore/Consensus/Blockmania/States/ViewChanged.cs, cypcore/Cryptography/Sloth.cs
Some minor refactoring, didn't touch access modifiers, but I think that there is some potential to make several class members private / protected as well. I suppose the more "correct" this is, the better an audit result will be.
The changes can serve as an input for documentation of code guidelines (and automatic enforcement thereof) to keep the project clean. I am not expecting you to accept all changes.
=> SK: Refactor unsused getters and class members initialization

.github/workflows/cypher.yml
=> feat(workflow): add linter

.github/workflows/release.yml
This is just a first step, nothing is done with the created releases yet.
- The Linux release shall be a single file.
- Fingerprints are to be added.
=> feat(release): create separate linux and win releases

cypcore/Extensions/AppExtenstions.cs, cypcore/Extensions/LoggerExtensions.cs, cypcore/Helper/Util.cs, cypcore/Ledger/MemoryPool.cs, cypcore/Ledger/Sync.cs, cypcore/Ledger/Validator.cs, cypcore/Models/TransactionProto.cs, cypcore/Network/LocalNode.cs, cypcore/Persistence/Repository.cs, cypcore/Persistence/StoreDb.cs, cypcore/Services/BlockService.cs, cypcore/Services/SerfService.cs, cypcore/cypcore.csproj, cypnode/Program.cs, cypnode/Startup.cs, cypnode/appsettings.json, cypnode/cypnode.csproj
Add contextual logging to make log messages more concise and less error-prone (e.g. manually typed method names in strings which do not lead to compilation errors and go undetected). Add line number to logging.
=> sk: feat(log): contextual logging

cypcore/Cryptography/Signing.cs, cypcore/Ledger/MemoryPool.cs, cypcore/Ledger/PosMinting.cs, cypcore/Ledger/Staging.cs, cypcore/Ledger/Sync.cs, cypcore/Ledger/Validator.cs, cypcore/Models/InterpretedProto.cs, cypcore/Models/MemPoolProto.cs, cypcore/Models/StagingProto.cs, cypcore/Models/TransactionProto.cs, cypcore/Network/LocalNode.cs, cypcore/Network/Peer.cs, cypcore/Serf/SerfClient.cs, cypcore/Services/BlockService.cs, cypcore/Services/MembershipService.cs, cypcore/Services/MemoryPoolService.cs, cypcore/Services/Rest/BlockRestService.cs, cypcore/Services/Rest/MemoryPoolRestService.cs, cypcore/Services/SerfService.cs
StagingProto.WaitingOn is not initialized and leads to a null object exception. The initialization of the lists is now moved into the creation of the object.
=> sk: fix: initialize StagingProto.WaitingOn member

cypcore/Ledger/Sync.cs, cypcore/Ledger/Validator.cs, test/unit/cypcore-test-unit/PoS/DistributionTests.cs
See discussion in issue #47 . There can be no forks due to Blockmania needing 2/3rd of all node for consensus on block ordering.
=> refactor(fork): remove forking

.gitignore
- Added entire publish folder to artifacts so they don't appear under vms.
=> Adds artifacts folder to ignore list.

.github/workflows/release.yml, install/linux/debian/rules
Build .deb files for all Linux platforms.
TODO: Adapt version in changelog to include version info in deb file.
=> feat(build): platform-dependent deb generation

.github/workflows/release.yml, install/linux/debian/changelog, install/linux/debian/changelog_create.sh
Add changelogs to deb builds. This is necessary to create .deb files with correct version information. Archive .deb artifacts as build artifact.
=> Feat build add changelog version deb

.gitignore, cypcore/Ledger/Graph.cs, cypcore/Ledger/MemoryPool.cs, cypcore/Ledger/PosMinting.cs, cypcore/Ledger/Validator.cs
Mostly clean-up/refactoring. Fix change lock-time.
=> Lock-time check for change amount

cypcore/Ledger/Graph.cs, cypcore/Ledger/PosMinting.cs, cypcore/Ledger/Validator.cs
Spendable age is not required as transactions are not referenced using an offset.
=> Remove change/coinstake spendable age

install/install.sh
patch successfully tested on archlinux-2021.08.01-x86_64
=> arch-release install.sh patch

install/install.sh
Create symlinks for libdl.so if the OS doesn't already have symlinks for them in the place we expect
=> * Create symlinks for libdl.so if required

core/Controllers/BlockController.cs, core/core.csproj, node/Configuration/Configuration.cs, node/node.csproj
- Fix address protocol format.
- Fix display error message on get block.
- Bump version
=> Fix for preview-1

install/install.sh
A new "--upgrade" option added to the install script, which will copy the node settings file and keys to a temporary location before installing the new software, and restoring them afterwards
This can also be used to "upgrade" a node to a different run user/group if the --runasuser/--runasgroup option is specified, although a custom user/group is not remembered by the upgrade (you need to specify them on every upgrade)
=> * Add upgrade option to install script

core/Ledger/Graph.cs, core/Network/Broadcast.cs, core/Network/P2PDevice.cs, core/Network/P2PDeviceApi.cs
- Refactor tcp non blocking when sending messages.
- Fix collection was modified.
=> Improvements 

core/Controllers/BlockController.cs, core/Ledger/Graph.cs, core/Ledger/Sync.cs, core/Ledger/Validator.cs, core/Models/PeerCooldown.cs, core/Network/P2PDeviceApi.cs, core/Network/PeerDiscovery.cs, core/core.csproj, node/Startup.cs, node/StartupExtensions/SwaggerExtensions.cs, node/appsettings.json, node/node.csproj
- Fix unhandled sanity check when saving the block exposed on the tcp channel 
- Added new rest api's
- - Supply
- - Emission
- - More
- Refactor synchronous decided winner
=> v0.0.67.0-preview4

core/Network/Broadcast.cs, core/Network/P2PDeviceReq.cs, core/Network/PeerDiscovery.cs, core/core.csproj, node/Program.cs, node/appsettings.json, node/node.csproj
- Fix app settings not found in base directory when installing with the bash script file.
- Fix peer unreadable or disconnecting.
=> Fixes for RC1

core/Ledger/Validator.cs, core/Models/Parameter.cs, core/Network/P2PDevice.cs, core/Network/P2PDeviceApi.cs, core/Network/PeerDiscovery.cs, core/Wallet/WalletSession.cs, core/core.csproj, node/node.csproj
- Reconnects peer as the sender, removes peer from the cooldown cache.
=> RC1 peer reconnect
